### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Grieferus** [skjelten/emusc#13]
Not really an issue here, since it's most likely my own stupidity, but when I assign MIDI input device and EmuSC (To specify, I installed latest pre-release, build-202205042314) seems to work, I receive no sound in FSMP.
Though, I might expect that it would sound exactly the same as the latest 0.1.8 build, so I probably wouldn't lose much.

P.S.: I really hope the work on EmuSC hasn't stopped, because I didn't really hear any news about it in 3 months already.

**Comment by Kitrinx** [comment]
I've identified some additional tables for the various curves in the control rom fairly recently. Skjelten mentioned to me not long ago that he is quite busy during the summer, and plans to return to it more regularly in the autumn.

**Comment by Grieferus** [comment]
Well, that's a relief.

**Comment by Grieferus** [comment]
So.
I found out (Relatively long ago), that shakuhachi has some sort of breath noise in it, yet I didn't find it in Trevor's soundfont.
Is it some sort of hidden sample or a missed one?

**Comment by Kitrinx** [comment]
Have you ever taken a look at the soundfont generated by my code? The presets have all the original channels that the real device used, as it's generated from the control and wave roms. Not all the parameters are applied properly though (particularly the TVF, I was struggling to make soundfonts use the same 5 point system as sc-55/mt32 did) but a lot of the data is pretty good.

https://github.com/Kitrinx/SC55_Soundfont

I also have a copy of this spreadsheet which I have added some additional info to which maps out the sc55's control rom decently:
https://docs.google.com/spreadsheets/d/1936CgqnIhdzoQAyyiRpklnvkqnG3GdGbMrXk3oQbPDE/edit?usp=sharing

**Comment by Grieferus** [comment]
I did a comparison, if you would like that.
https://drive.google.com/file/d/1EQrTMKsZS0WLC6mgmVDCDlATjlAzYIyz/view?usp=sharing

**Comment by Grieferus** [comment]
Either way, I wish you all best luck, lads!

**Comment by Kitrinx** [comment]
It uses
0x004E - SHAKU and
0x004F - BREATH voices
so yes, two voice instrument with breath noise as you noted

**Comment by Kitrinx** [comment]
Here's a WIP copy of a generated version of my soundfont. It has the breath noise you noted:
https://drive.google.com/file/d/1NgX01G8VLVfhC0vEaVkQeHOQKxLUUIkv/view?usp=sharing

**Comment by Grieferus** [comment]
Thank you for enlightening me.

**Comment by skjelten** [comment]
The emusc application has been rewritten and includes a number of fixes related to both MIDI and audio. I'll just close this issue now. Feel free to reopen if you still have issues.
