### ISSUE TITLE
Segfault after building on Windows 10 (MSYS 2, LTSC)

### ISSUE THREAD

**Issue by nehochupechatat** [skjelten/emusc#16]
Right after powering it on, it crashes and give me a segfault. Also, to even get it to compile I had to add a custom M_PI definition.
Followed the instructions.

**Comment by skjelten** [comment]
There are no known bugs that should trigger a segfault, but it could be a number of things, like corrupt ROM files, audio setup issues etc. Do you have gdb installed and know how to use it? I basically boils down to:
```
gdb ./emusc
run
bt (after it have segfaulted)
```
If you could paste the output of gdb it would be of great help to identify the root cause of your crash.

I have not verified that the M_PI definition exists on all platforms / compilers, but I'll have a look at it.

**Comment by nehochupechatat** [comment]
[New Thread 21728.0x5a30]
POWER ON
EmuSC: GS mode initialized
[New Thread 21728.0x5a50]

Thread 1 received signal SIGSEGV, Segmentation fault.
Emulator::_start_audio_subsystem (this=this@entry=0x1a75fa54570) at C:/msys64/home/nehochupechatat/emusc/emusc/src/emulator.cc:271
271       _audioOutput->start();
(gdb) bt
#0  Emulator::_start_audio_subsystem (this=this@entry=0x1a75fa54570)
    at C:/msys64/home/nehochupechatat/emusc/emusc/src/emulator.cc:271
#1  0x00007ff73ec0cae6 in Emulator::start (this=0x1a75fa54570)
    at C:/msys64/home/nehochupechatat/emusc/emusc/src/emulator.cc:129
#2  0x00007ff73ec0f113 in MainWindow::power_switch (this=0x4d00bffad0,
    newPowerState=<optimized out>)
    at C:/msys64/home/nehochupechatat/emusc/emusc/src/main_window.cc:204
#3  0x00007ffcc1ecde33 in void doActivate<false>(QObject*, int, void**) ()
   from /ucrt64/bin/Qt5Core.dll
#4  0x00007ffcc1080412 in QAbstractButtonPrivate::emitClicked() () from /ucrt64/bin/Qt5Widgets.dll
#5  0x00007ffcc1082018 in QAbstractButtonPrivate::click() () from /ucrt64/bin/Qt5Widgets.dll
#6  0x00007ffcc1082205 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#7  0x00007ffcc0fd6770 in QWidget::event(QEvent*) () from /ucrt64/bin/Qt5Widgets.dll
#8  0x00007ffcc0f97bfe in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#9  0x00007ffcc0f9ffbc in QApplication::notify(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#10 0x00007ffcc1de56e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Core.dll
#11 0x00007ffcc0f9dda0 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /ucrt64/bin/Qt5Widgets.dll
#12 0x00007ffcc1288e3e in QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(QGraphicsSceneMouseEvent*) () from /ucrt64/bin/Qt5Widgets.dll
#13 0x00007ffcc1276acd in QGraphicsItem::sceneEvent(QEvent*) () from /ucrt64/bin/Qt5Widgets.dll
#14 0x00007ffcc1295ddb in QGraphicsScenePrivate::sendMouseEvent(QGraphicsSceneMouseEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /ucrt64/bin/Qt5Widgets.dll
#15 0x00007ffcc129b8c9 in QGraphicsScene::mouseReleaseEvent(QGraphicsSceneMouseEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#16 0x00007ffcc12a8742 in QGraphicsScene::event(QEvent*) () from /ucrt64/bin/Qt5Widgets.dll
#17 0x00007ffcc0f97bfe in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#18 0x00007ffcc1de56e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Core.dll
#19 0x00007ffcc12bf899 in QGraphicsView::mouseReleaseEvent(QMouseEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#20 0x00007ffcc0fd6770 in QWidget::event(QEvent*) () from /ucrt64/bin/Qt5Widgets.dll
#21 0x00007ffcc107b402 in QFrame::event(QEvent*) () from /ucrt64/bin/Qt5Widgets.dll
#22 0x00007ffcc1de4c44 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*)
    () from /ucrt64/bin/Qt5Core.dll
#23 0x00007ffcc0f97bee in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#24 0x00007ffcc0f9ffbc in QApplication::notify(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#25 0x00007ffcc1de56e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Core.dll
#26 0x00007ffcc0f9dda0 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () from /ucrt64/bin/Qt5Widgets.dll
#27 0x00007ffcc0fee00b in QWidgetWindow::handleMouseEvent(QMouseEvent*) ()
   from /ucrt64/bin/Qt5Widgets.dll
#28 0x00007ffcc0ff12b8 in QWidgetWindow::event(QEvent*) () from /ucrt64/bin/Qt5Widgets.dll
#29 0x00007ffcc0f97bfe in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
--Type <RET> for more, q to quit, c to continue without paging--
   from /ucrt64/bin/Qt5Widgets.dll
#30 0x00007ffcc1de56e8 in QCoreApplication::sendSpontaneousEvent(QObject*, QEvent*) ()
   from /ucrt64/bin/Qt5Core.dll
#31 0x00007ffcc15a1904 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /ucrt64/bin/Qt5Gui.dll
#32 0x00007ffcc157b47c in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /ucrt64/bin/Qt5Gui.dll
#33 0x00007ffcc1e3f9d0 in QEventDispatcherWin32::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /ucrt64/bin/Qt5Core.dll
#34 0x00007ffcc530f3f5 in QWindowsGuiEventDispatcher::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /ucrt64/share/qt5/plugins/platforms/qwindows.dll
#35 0x00007ffcc1de3ad3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /ucrt64/bin/Qt5Core.dll
#36 0x00007ffcc1dec227 in QCoreApplication::exec() () from /ucrt64/bin/Qt5Core.dll
#37 0x00007ff73ecd14df in main (argc=<optimized out>, argv=<optimized out>)
    at C:/msys64/home/nehochupechatat/emusc/emusc/src/emusc.cc:38

**Comment by nehochupechatat** [comment]
I was using my Jabra 65 USB headphones. Tried switching audio output to the laptop speakers, it didn't recognize MIDI events sent through the loopMIDI virtual cable.

**Comment by nehochupechatat** [comment]
It did recognize the events but no sound

**Comment by skjelten** [comment]
So if I understand you correctly:
* Selecting Jabra 65 USB headphones makes emusc crash on power on
* Selecting laptop speakers EmuSC starts OK, but you cannot hear any audio

I assume you have selected "Win32" and "loopMIDI" in the MIDI configuration dialog? Do the bars in the part display indicate any notes being played? (play a MIDI file or hit a tangent several times and you should see that the display indicates notes being played).

**Comment by nehochupechatat** [comment]
Yes, the bars do indicate notes being sent. What's even weirder is that none of these issues were there in the old commandline based release from October.

**Comment by skjelten** [comment]
This is probably a dumb question, but have you tried to rotate the volume dial on the left side? I just compiled EmuSC in windows and I can see that the volume is set to 0 by default for some reason.

**Comment by nehochupechatat** [comment]
When I first tried turning the dial, it didn't work. I recompiled, rebooted, reconfigured... Seems to work with Jabra 65 and the volume dial turned up. Thanks!

**Comment by skjelten** [comment]
Ok, good to hear! I have also just tested with a USB headset and it works fine.

I do notice a few bugs though that seems more prevalent on windows. Some of them are already fixed, but being held back since they are a part of a bigger commit. I will try to have round of bug/stability fixes for windows later.

**Comment by ljcool2006** [comment]
I am still having this issue.

**Comment by skjelten** [comment]
Hi ljcool2006,

Since this ticket was closed last year, please create a new one and I'll try to help. Also, please describe when the program segfaults (on startup? before or after you made the initial ROM & audio configuration?), which OS you are running and gdb output if you are able to (see 2nd. comment in this ticket).
