### ISSUE TITLE
SD series support in the future? 

### ISSUE THREAD

**Issue by MetalMaxMX** [skjelten/emusc#2]
Hey, I saw your project on a Github search and I was curious about it due to it being an interesting thing you're tackling with this, that is the emulation of proper SC in the future instead of needing to rely on soundfonts which would make things like mt32-pi but instead sc55-pi possible and all! And I was wondering if support for the SD series could also be considered in the farther future? (After the SC-series, or at least SC-55 and SC-88 have been dealt with) since SD-series also are part of the Sound Canvas series by Edirol/Roland and all. 

Cheers!
MetalMaxMX

**Comment by skjelten** [comment]
Hi MetalMaxMX,

Sorry for the late reply! I'm afraid I don't know much about the SD-series, so it will be difficult for me to evaluate the feasibility of supporting them in emusc in the future. The biggest hurdles for emulating the SD-series will probably be to:
 1: Figure out the exact control ROM structure
 2: Decrypt the PCM ROMs

We could be lucky and that they use the exact same structure as the SC-series, but that is not very likely. SD-series also supports GM2 and probably quite a few other features not available in the earlier SC-series.

So whether emusc will ever support the SD-series is too early to tell, but I would not hold my breath. That said, if someone got their hands on the SD-series ROM files and figured out the structures and encryption, I'm pretty sure forking emusc could be an efficient way of prototyping a new emulator.
