### ISSUE TITLE
Not detected by aplaymidi, no sound.

### ISSUE THREAD

**Issue by rderooy** [skjelten/emusc#29]
Fedora 39 x86_64 using latest git code

Starting emusc:
```bash
$ LD_LIBRARY_PATH=/usr/local/lib64 emusc -p
QSocketNotifier: Can only be used with threads started with QThread
EmuSC: Audio output [PulseAudio] successfully initialized
 -> s16le 2ch 44100Hz
EmuSC: MIDI sequencer [ALSA] client started at address 128
```

Emusc starts up and seems fine.
![image](https://github.com/skjelten/emusc/assets/17701098/8ceeebd5-6cc3-444f-b046-ef5ae4167063)

But checking with `aplaymidi`, it does not see the device:

```bash
$ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
```

Regardless, using `aplaymidi` to play a MIDI file seems to do something:
```bash
$ aplaymidi -p 128:0 CANYON.MID
```

The emusc display changes:
![image](https://github.com/skjelten/emusc/assets/17701098/528a7c77-b483-481b-a6c0-0f451fe6c890)

And there are a lot of emusc log messages, but no sound:
```
EmuSC: MIDI input event [Port subscribed]
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
Polyphonic key pressure not implemented (ch=, key=12, value=)
Polyphonic key pressure not implemented (ch=, key=12, value=)
Polyphonic key pressure not implemented (ch=, key=12, value=)
Polyphonic key pressure not implemented (ch=, key=3, value=)
Polyphonic key pressure not implemented (ch=, key=3, value=)
Polyphonic key pressure not implemented (ch=, key=3, value=)
Polyphonic key pressure not implemented (ch=, key=2, value=)
Polyphonic key pressure not implemented (ch=, key=2, value=)
Polyphonic key pressure not implemented (ch=, key=2, value=)
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
EmuSC: New note on ignored due to voice limit
```
The above errors just continue flowing as long as aplaymidi is running.

**Comment by skjelten** [comment]
I have not used `aplaymidi -l` before and cannot say for sure why emusc does not show up. I might have a look at aplaymidi source later to see why, but if you use `aconnect -l` (or `aconnect -o`) you should see EmuSC listed.

When it comes to the lack of audio output I guess there is a problem with the pulse audio output driver on your setup (based on the fact that you quickly run into voice limits). Do you have the option to try ALSA or JACK output? All the emusc linux audio drivers are in need of some improvements, but the pulse audio driver is the weakest.

**Comment by rderooy** [comment]
Considering the emusc display does not change when it is "playing", I suspect the issue may not be the sound driver. But since I am using PipeWire, I guess I should be able to try Jack, although I have no experience with it.

**Comment by rderooy** [comment]
A quick test with `mt32emu-qt`:
```bash
$ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
128:0    Munt MT-32                       Standard
$ aplaymidi -p 128:0 CANYON.MID
```
Playback works this way with Munt.

**Comment by rderooy** [comment]
With `emusc` running:
```
$ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
$ aconnect -l
client 0: 'System' [type=kernel]
    0 'Timer           '
	Connecting To: 144:0
    1 'Announce        '
	Connecting To: 144:0
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'EmuSC' [type=user,pid=105964]
    0 'EmuSC           '
client 144: 'PipeWire-System' [type=user,pid=2797]
    0 'input           '
	Connected From: 0:1, 0:0
client 145: 'PipeWire-RT-Event' [type=user,pid=2797]
    0 'input           '
$ aconnect -o
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'EmuSC' [type=user,pid=105964]
    0 'EmuSC
```

And for comparison with `mt32emu-qt`:
```
$ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
128:0    Munt MT-32                       Standard
$ aconnect -l
client 0: 'System' [type=kernel]
    0 'Timer           '
	Connecting To: 144:0
    1 'Announce        '
	Connecting To: 144:0
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'Munt MT-32' [type=user,pid=106092]
    0 'Standard        '
client 144: 'PipeWire-System' [type=user,pid=2797]
    0 'input           '
	Connected From: 0:1, 0:0
client 145: 'PipeWire-RT-Event' [type=user,pid=2797]
    0 'input           '
$ aconnect -o
client 14: 'Midi Through' [type=kernel]
    0 'Midi Through Port-0'
client 128: 'Munt MT-32' [type=user,pid=106092]
    0 'Standard        '
```

**Comment by rderooy** [comment]
First of all, I don't see a JACK output option in the audio configuration menus. Only "Pulse", "ALSA" and "Null".

Changing it to ALSA, and setting "Audio device" to "PipeWire Sound Server" allows it to work.
![image](https://github.com/skjelten/emusc/assets/17701098/ce3305c3-eae6-44b8-ba9d-b843fd767635)

![image](https://github.com/skjelten/emusc/assets/17701098/50b1858e-66cd-4f1e-9fca-0401c2e47834)

**Comment by skjelten** [comment]
Good to see that you got it to work. The ALSA driver has normally less latency than the pulse driver, so it is the preferred solution when possible.

To have JACK as an option you will need to install the JACK development libraries and recompile EmuSC with JACK support, but there is no need for it if you have ALSA working fine.

Also, I just committed a fix that adds correct MIDI capabilities to the ALSA MIDI port. EmuSC should from now on be visible in `playmidi -l` and other MIDI applications that filter on the SND_SEQ_PORT_TYPE_MIDI_GENERIC flag being set.

**Comment by rderooy** [comment]
Thank you!

```bash
$ aplaymidi -l
 Port    Client name                      Port name
 14:0    Midi Through                     Midi Through Port-0
128:0    EmuSC                            EmuSC Midi Input
```
