### ISSUE TITLE
Don't know how to configure ROM files

### ISSUE THREAD

**Issue by dagjomar** [skjelten/emusc#34]
The first time instructions tell me that I need to configure the ROM files, and when I go to preferences I see the place to configure this. But I don't know what a ROM file is or where to find it? Have tried to look a bit in various folders in the project but not able to find anything related.

<img width="476" alt="Screenshot 2024-03-10 at 13 49 26" src="https://github.com/skjelten/emusc/assets/416408/33409434-dc27-4d99-a584-8092d5c8b5fa">

**Comment by dagjomar** [comment]
I see in the emusc readme, it says
> (...) In addition you will need the original control and PCM ROMs.

So I guess I can't run this app without some original files? How would one get these files?

**Comment by Grounded0** [comment]
These are copyrighted by Roland and have to be acquired by other means.

**Comment by dagjomar** [comment]
Understood. Then this ticket can be closed.

Is it possible to just use/import the library manually and make it produce
sound then?

Wondering what I can expect to be able to do with this.

Dag Jomar Mersland
***@***.***
(+47 994 75 892)
