### ISSUE TITLE
Is there supposed to be no resample filtering?

### ISSUE THREAD

**Issue by UnBeatWaterGH** [skjelten/emusc#41]
In EmuSC there seems to be no resample filtering. I don't know if it works on your system or not, so I can't know if there is no resample filtering on your system.
On my system it sounds like if you took a high-quality sound and applied a bit-crusher to it, that's the kind of sound I hear.
Maybe you're just being faithful to the original system but I don't know.

Without resample filtering the sound feels very electronic or digital.

**Comment by skjelten** [comment]
You are right that there is currently no resample filtering, and I absolutely think that we need it to be able to recreate properly the audio of these synths. With finally fixing the long standing pitch calculation issue yesterday I think this is a natural next step.

My time is a bit stretched on this project, but if you, or anybody else following this project, have time and interest to work on this I will be very happy to participate and support with what I know.

**Comment by mmontag** [comment]
I would like to take a shot at cubic resampling.

**Comment by mmontag** [comment]
I was thinking of using FluidSynth as a rough guide, since it has such a similar usecase and supports 4 interpolation types (none, linear, cubic, sinc) with variable rate resampling.  And it is super battle-tested.  

Do you know of other open source projects that do variable-rate resampling without using dependencies?

**Comment by skjelten** [comment]
When looking for inspiration I sometimes look at timidity (really hard to read code, but in many areas quite focused on creating sounds similarly to the SC-88), Munt and fluidsynth (usually the easiest to read code).

In case of resampling, Munt has an [abstraction layer](https://github.com/munt/munt/tree/master/mt32emu/src/srchelper) that allows it to either use their own internal resampler or external libraries. For timidity I am pretty sure I have seen references to resampling as well, but fluidsynth is most likely way more modern and easier to get inspiration from.

**Comment by mmontag** [comment]
Can we close this issue?

**Comment by skjelten** [comment]
Sure!
