### ISSUE TITLE
When turning off and back on, the current value of the volume knob doesn't get used.

### ISSUE THREAD

**Issue by UnBeatWaterGH** [skjelten/emusc#42]
Whenever I turn the synth off and then back on, it does not use the value of the Volume knob, instead it uses a starting value. It does this without changing the value of the knob itself. To fix this, I turn the knob a bit every time after I "power cycle" the synth through the power button.

**Comment by skjelten** [comment]
I have noticed this as well, should be pretty trivial to fix. On my todo list after the PR that has been waiting.

**Comment by skjelten** [comment]
Just pushed a fix for this to the GIT repo. Please reopen this issue if you still have problems.
