### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Grieferus** [skjelten/emusc#44]
It's not really an issue and more of a genuine interest.
As you might already know, there's Nuked-SC55 emulator, which despite being in early stage, already sounds great. And so, I want to clarify the differences between your projects to avoid possible confusion in the future.

**Comment by skjelten** [comment]
I have not had time to try the Nuked SC55 emulator yet, but to my understanding this is a project that emulates the hardware used in the SC-55 line of synths. When the CPU is properly emulated you can basically execute the content of the control ROM much the same way the original hardware did. Emusc on the other hand is written in native code for each platform it runs on, and tries to emulate the SC-55 line synths by re-implementing the synths functionality in C++ (much like what Munt does for the MT-32 / CM line of synths).

These projects does not share any code or basically have anything in common as they have two completely different approaches, albeit sharing a very similar end goal. It might well be that there is little interest for emusc now that there exist a free and close to perfect SC-55 audio emulator. Time will tell, but as long as I enjoy working on it I will continue to improve emusc when time permits.

I will add a reference to Nuked SC55 emulator with some extra information in the README file shown on github next time I update it.

**Comment by Grounded0** [comment]
Nuked-SC55 is currently licenced with MAME licence which prohibits GPL projects from adopting it. I wish that this project will head for its initial release soon as its much easier to gather community support after the initial release is out since it establishes a baseline for the project.

**Comment by Grieferus** [comment]
> I have not had time to try the Nuked SC55 emulator yet, but to my understanding this is a project that emulates the hardware used in the SC-55 line of synths. When the CPU is properly emulated you can basically execute the content of the control ROM much the same way the original hardware did. Emusc on the other hand is written in native code for each platform it runs on, and tries to emulate the SC-55 line synths by re-implementing the synths functionality in C++ (much like what Munt does for the MT-32 / CM line of synths).
> 
> These projects does not share any code or basically have anything in common as they have two completely different approaches, albeit sharing a very similar end goal. It might well be that there is little interest for emusc now that there exist a free and close to perfect SC-55 audio emulator. Time will tell, but as long as I enjoy working on it I will continue to improve emusc when time permits.
> 
> I will add a reference to Nuked SC55 emulator with some extra information in the README file shown on github next time I update it.

Thank you for explaining! And no, I, for one, am still interested in EmuSC and wait impatiently for its release.

**Comment by mmontag** [comment]
To build on @skjelten's comment (please correct me if I'm wrong):

emusc is rather like the [sm64](https://github.com/n64decomp/sm64) or [Zelda](https://zelda64.dev/) decompilation projects - where the source is "reconstructed" in a modern developer environment. The end goal is to arrive at something akin to the original source, which opens up the possibility for modification and [improvements](https://www.youtube.com/watch?v=t_rzYnXEQlE).

Nuked SC55 instead makes no effort to decompile the firmware but instead emulates all the chips that it runs on. The result is incredibly faithful to the hardware, but difficult to extend.

**Comment by Grieferus** [comment]
So, that's why it's impossible for NukedSC to extend polyphony, for example.

**Comment by skjelten** [comment]
> Nuked-SC55 is currently licenced with MAME licence which prohibits GPL projects from adopting it. I wish that this project will head for its initial release soon as its much easier to gather community support after the initial release is out since it establishes a baseline for the project.

It has been 2 years in the making, so I agree that it is time for a release. I started earlier today to do some cleanups and is now investigating how to make a release in GitHub, what documentation that needs an update and making binary packages for windows and macOS. For Windows I guess a zip-file with binaries suffice for now.

Just keep in mind that emusc is currently nowhere near nuked SC55 in terms of audio quality.

**Comment by Grieferus** [comment]
Hm... Have you ever tried to unscramble Motorola and Hitachi ROMs? Maybe, they're responsible for the exact effects but I don't know for sure. Besides, I do understand that it will slower the development even further, possibly leading to emusc getting stuck in development hell.

**Comment by skjelten** [comment]
> To build on @skjelten's comment (please correct me if I'm wrong):
> 
> emusc is rather like the [sm64](https://github.com/n64decomp/sm64) or [Zelda](https://zelda64.dev/) decompilation projects - where the source is "reconstructed" in a modern developer environment. The end goal is to arrive at something akin to the original source, which opens up the possibility for modification and [improvements](https://www.youtube.com/watch?v=t_rzYnXEQlE).
> 
> Nuked SC55 instead makes no effort to decompile the firmware but emulates the microcontroller chips that it runs on. This is more like playing Zelda in a console emulator. The Zelda game ROM is passed unmodified to the emulation software. The result is very faithful to the hardware, but difficult to extend.

That youtube video of super mario 64 improvements you linked to was really fascinating :slightly_smiling_face:

**Comment by Grieferus** [comment]
> To build on @skjelten's comment (please correct me if I'm wrong):
> 
> emusc is rather like the [sm64](https://github.com/n64decomp/sm64) or [Zelda](https://zelda64.dev/) decompilation projects - where the source is "reconstructed" in a modern developer environment. The end goal is to arrive at something akin to the original source, which opens up the possibility for modification and [improvements](https://www.youtube.com/watch?v=t_rzYnXEQlE).
> 
> Nuked SC55 instead makes no effort to decompile the firmware but emulates the microcontroller chips that it runs on. This is more like playing Zelda in a console emulator. The Zelda game ROM is passed unmodified to the emulation software. The result is very faithful to the hardware, but difficult to extend.

Speaking in Doom terms, Nuked-SC55 is DOSBox and EmuSC is Crispy Doom.

**Comment by Grounded0** [comment]
> Just keep in mind that emusc is currently nowhere near nuked SC55 in terms of audio quality.

Doesn't matter. Almost everything is pretty rough in their initial release anyway. Main thing is to get it out because it shows commitment to the project and hopefully will get more people onboard as there's an initial project baseline then.

**Comment by skjelten** [comment]
Since the README have been updated and the first release is complete, I will just close this issue.
