### ISSUE TITLE
First release bug

### ISSUE THREAD

**Issue by Grieferus** [skjelten/emusc#47]
I realise that it's most likely on my part, but I have this issue when trying to power up EmuSC.
![emusc_failure](https://github.com/skjelten/emusc/assets/105528501/8ceb6eca-2f5a-459e-a4ad-1598d03f1007)
Control ROM version is 1.21. Maybe another version should be used?

**Comment by Grieferus** [comment]
Apparently, EmuSC doesn't have ASC-II support.

**Comment by skjelten** [comment]
I think this is a valid bug report that needs attention, so re-opening the issue.

Emusc client is using QString and QFile classes and has no problem using non-ASCII characters, but libemusc on the other hand uses only standard libc++. This makes libemusc very portable and lightweight, but extra care must be taken when receiving non-ASCII characters from the client.

Probably not the most urgent issue, but should be fixed somehow.

**Comment by skjelten** [comment]
Commit b506988 should fix this, please reopen if the problem persist.
