### ISSUE TITLE
Compile the project for Windows

### ISSUE THREAD

**Issue by Kappa971** [skjelten/emusc#5]
I can't in any way compile the project for Windows with MinGW64 (MSYS2). On Windows it is much more practical and functional to compile with Visual Studio (and vcpkg).
Other projects make use of CMake which, reading on the internet, seems more versatile than the method used now. But I'm not an expert so I might be wrong.

**Comment by skjelten** [comment]
I'm not much of a Windows user, so I have very limited knowledge on how this could be done smarter on Windows. That said, I have found two ways to compile the project for Windows:

1: Install mingw in Linux and use the --host= parameter in the configure script to specify the cross compiler. It took me an hour to get it right, but then it's a very elegant solution (if you have your working source repository in Linux)

2: Install msys2 and mingw in Windows just as you mentioned. I tested this solution yesterday and it works very well. Start by installing msys2 and then use pacman to install automake, autoconf and mingw-w64-x86_64-gcc/make/binutils (you probably need a few more - recommend to just install base-devel). Make sure to update the PATH to include /mingw64 i.e. "export PATH=$PATH:/mingw64/bin". If all is well you should be able to run "g++" from the command line. Then run "./autogen.sh", "./configure" and "make" as normal. Tip: if you add "-static" to the linker flags in the src/Makefile you can use the emusc.exe on other computers as well without installing msys og mingw.

Regarding automake vs CMake, I'm pretty sure most of the internett would agree with you that CMake is a more modern and flexible solution. I just happened to use the old solution I know (automake) the day I started to code on this project, and didn't expect the project to succeed to a degree that this would become an issue :slightly_smiling_face:

**Comment by Kappa971** [comment]
Thanks, I'll see if I can get an exe out 🙂

**Comment by ThatRetroGuy** [comment]
> Thanks, I'll see if I can get an exe out 🙂

Hey! didn't you work on some emulator before?

**Comment by Kappa971** [comment]
> 2: Install msys2 and mingw in Windows just as you mentioned. I tested this solution yesterday and it works very well. Start by installing msys2 and then use pacman to install automake, autoconf and mingw-w64-x86_64-gcc/make/binutils (you probably need a few more - recommend to just install base-devel). Make sure to update the PATH to include /mingw64 i.e. "export PATH=$PATH:/mingw64/bin". If all is well you should be able to run "g++" from the command line. Then run "./autogen.sh", "./configure" and "make" as normal. Tip: if you add "-static" to the linker flags in the src/Makefile you can use the emusc.exe on other computers as well without installing msys og mingw.

Nothing to do, it doesn't work:
```
$ ./autogen.sh
processing .
Running aclocal  ...
Running autoheader...
Running automake --gnu  ...
configure.ac:25: installing './compile'
configure.ac:6: installing './config.guess'
configure.ac:6: installing './config.sub'
configure.ac:11: installing './install-sh'
configure.ac:11: installing './missing'
Makefile.am: installing './INSTALL'
src/Makefile.am: installing './depcomp'
Running autoconf ...
```
```
$ ./configure
configure: loading site script /etc/config.site
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32
checking target system type... x86_64-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for audio API...
checking for gcc... gcc
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for snd_seq_open in -lasound... no
configure: WARNING: ALSA library not found and will not be supported
checking for main in -lpulse... no
configure: WARNING: PulseAudio library not found and will not be supported
checking for main in -lwinmm... yes
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for CoreAudio/CoreAudio.h... no
configure: WARNING: CoreAudio library not found and will not be supported
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands


  EmuSC installation summary:
-=============================-
Host platform: x86_64-w64-mingw32

MIDI APIs:
  * ALSA  : no
  * Core  : no
  * Win32 : yes

Audio APIs:
  * ALSA  : no
  * Core  : no
  * Null  : yes
  * Pulse : no
  * Win32 : yes

Have fun!
```
```
$ make
make  all-recursive
make[1]: ingresso nella directory «/home/kappa/emusc»
Making all in src
make[2]: ingresso nella directory «/home/kappa/emusc/src»
i686-w64-mingw32-g++-posix -DHAVE_CONFIG_H -I. -I..  -I.. -I/mingw64/include    -g -O2 -D__WIN32__ -MT emusc.o -MD -MP -MF .deps/emusc.Tpo -c -o emusc.o emusc.cc
make[2]: i686-w64-mingw32-g++-posix: No such file or directory
make[2]: *** [Makefile:434: emusc.o] Errore 127
make[2]: uscita dalla directory «/home/kappa/emusc/src»
make[1]: *** [Makefile:370: all-recursive] Errore 1
make[1]: uscita dalla directory «/home/kappa/emusc»
make: *** [Makefile:311: all] Errore 2
```
I installed: mingw-w64-x86_64-make, mingw-w64-x86_64-gcc, automake, autoconf, base-devel

**Comment by shermp** [comment]
It looks like you might be launching MSYS2 using the `MSYS2 MSYS` shell. That shell is designed for compiling posix applications for use withing MSYS2 itself.

Instead, you need to be running the `MSYS2 MinGW 64-bit` shell. There is no need to set any PATH variables, it's all done automatically by the shortcut. Within that shell, you will probably need to re-run `configure` to generate a new Makefile.

For cross platform development, I really would recommend switching to another build system like CMake or Meson. Autotools is REALLY slow in MSYS2, especially the Automake generated Makefiles.

**Comment by Kappa971** [comment]
> Instead, you need to be running the `MSYS2 MinGW 64-bit` shell. There is no need to set any PATH variables, it's all done automatically by the shortcut. Within that shell, you will probably need to re-run `configure` to generate a new Makefile.

That's what I'm doing, I also specified it. I also specified what I installed.

> I installed: mingw-w64-x86_64-make, mingw-w64-x86_64-gcc, automake, autoconf, base-devel.
> I'm obviously running the MINGW64/MSYS2 console.

**Comment by skjelten** [comment]
> 
> EDIT In src/Makefile I had to manually edit line 201: `CXX = i686-w64-mingw32-g++-posix` to `CXX = x86_64-w64-mingw32-g++`. Now compile, but I don't understand what I'm doing wrong... why is i686-w64-mingw32-g++-posix set?

This is done because EmuSC uses the C++11 thread class, which is implemented by (posix) pthread in g++. Sometimes g++ is compiled with C++11 thread support and sometimes without. It's been quite common to have both versions available, and in those cases you have one binary called g++ and another called g++-posix (to indicate posix thread support). I expect this to be a thing of the past pretty soon as pthread support in g++ have been "stable" for years.

The mingw-w64 g++ version you installed includes the thread functionality via winpthread in its default build (see "Headers, Libraries and Runtime" in the front page of [MinGW-w64 homepage](https://www.mingw-w64.org). It is therefore no need for the separate g++-posix binary and your fix in the makefile is 100% correct. Why exactly the configure script appended the "-posix" suffix to g++ in your Makefile I'm not sure of, it did not do that on my machine. But it does not matter, your current setup is correct.

**Comment by Kappa971** [comment]
I state that I don't know anything about this stuff, in the `configure.ac` file I noticed this:
```
dnl   Setting some architecture dependent compiler options
dnl -======================================================-
case "$host" in
     	*-*-mingw32*)
		LDFLAGS="$LDFLAGS -static-libstdc++ -static"
		CXX=i686-w64-mingw32-g++-posix
		;;

```

**Comment by skjelten** [comment]
> I state that I don't know anything about this stuff, in the `configure.ac` file I noticed this:
> 
> ```
> dnl   Setting some architecture dependent compiler options
> dnl -======================================================-
> case "$host" in
>      	*-*-mingw32*)
> 		LDFLAGS="$LDFLAGS -static-libstdc++ -static"
> 		CXX=i686-w64-mingw32-g++-posix
> 		;;
> ```
> 
> It is as if I'm trying to decipher a hieroglyph grin but it seems that if the "host" contains the string `*-*-mingw32*` (in this case `x86_64-w64-mingw32),` it will always set `CXX=i686-w64-mingw32-g++-posix`

And there you have it! If the configure script detects an architecture matching "*-*-mingw32*)" it will override CXX to "i686-w64-mingw32-g++-posix". That's exactly why you had to change it. I'll improve the configure script later (or switch to CMake or something else). The macosx part is in even worse condition.

Closing this ticket as I think we have thoroughly solved the issue of compiling EmuSC for Windows :slightly_smiling_face:
