### ISSUE TITLE
"Unable to create config directory" error + one issue I've noticed. 

### ISSUE THREAD

**Issue by trevor0402** [skjelten/emusc#8]
Hello! Phenomenal work so far, I've been trying to compile this under Windows and I get a "unable to create config directory" error. Is there a way I can fix that? 

Also, I did test this under Linux and it sounds wonderful. But I've noticed some issues with the pitch correction related stuff. Like with DOOM's E1M1, the Overdrive Guitar and Distortion Guitar samples are slightly off-tune. I think the Ride Bell also is pitched a bit high, as if the root key value was incorrect. 

If there is any way I could help too, please let me know. I was working on an SC-55 SoundFont before but gave up after realizing the SoundFont 2.0 standard couldn't represent this particular synth.

**Comment by nmcgill** [comment]
There are pre-compiled builds (incl Windows) that you could try here: https://github.com/nmcgill/emusc/releases

I have tested the Windows build and the config directory seems to be working as expected

**Comment by Grieferus** [comment]
> There are pre-compiled builds (incl Windows) that you could try here: https://github.com/nmcgill/emusc/releases
> 
> I have tested the Windows build and the config directory seems to be working as expected. Hope this helps!

Maybe I should post it as a separate issue, but still.
When I try to launch EmuSC (Latest pre-compiled build, if to be specific), it says "Unable to open control ROM".

**Comment by Kappa971** [comment]
In the `EmuSC` folder, create the `SC-55` folder and paste all the ROMs into it. In the configuration file try to write `./SC-55/<rom_name>` for all required roms. 

Currently, however, I don't recommend using EmuSC (as a user, I'm not the developer), it still needs work, but this is just my opinion.

**Comment by Grieferus** [comment]
> In the `EmuSC` folder, create the `SC-55` folder and paste all the ROMs into it. In the configuration file try to write `./SC-55/<rom_name>` for all required roms.
> 
> Currently, however, I don't recommend using EmuSC (as a user, I'm not the developer), it still needs work, but this is just my opinion.

Should I write the full path?

**Comment by Grieferus** [comment]
> In the `EmuSC` folder, create the `SC-55` folder and paste all the ROMs into it. In the configuration file try to write `./SC-55/<rom_name>` for all required roms.
> 
> Currently, however, I don't recommend using EmuSC (as a user, I'm not the developer), it still needs work, but this is just my opinion.

Okay, I'm feeling kinda dumb right now.
Would you please send video tutorial?

**Comment by Kappa971** [comment]
EmuSC folder:
![scr1](https://user-images.githubusercontent.com/62349018/168795429-c4156bc3-dbf2-47ca-83d1-9214184d6da2.png)

Inside EmuSC folder:
![scr2](https://user-images.githubusercontent.com/62349018/168795498-ead7ca3a-21c7-4221-8178-a632a17f4f06.png)

Inside SC-55 folder:
![scr3](https://user-images.githubusercontent.com/62349018/168795542-559e3942-3b6e-42da-a11d-c147eced943e.png)

in `C:\users\%username%\appdata\local`
`emusc.conf`:
```
# Configuration file for EmuSC

# MIDI input system [ alsa | win32 | core | keyboard ]
input = win32

# MIDI input device [0 .. ]. Specifies MIDI device id (win32 only)
input_device=0

# Audio output system [ alsa | pulse | win32 | core | null ]
output = win32

# Output device, e.g. 'default' or 'hw:0.1' for alsa.
output_device=default
# Output buffer time in us. Default = 75000
output_buffer_time=75000

# Output period time in us. Used for alsa. default = 25000
output_period_time=25000

# ROM files
control_rom = ./SC-55/roland_r15209363.ic23

# Some models use up 3 PCM ROMs (must be in correct order)
pcm_rom_1 = ./SC-55/roland-gss.a_r15209276.ic28
pcm_rom_2 = ./SC-55/roland-gss.b_r15209277.ic27
pcm_rom_3 = ./SC-55/roland-gss.c_r15209281.ic26
```

**Comment by Grieferus** [comment]
Thank you.

**Comment by Grieferus** [comment]
Now, the only thing is to make it work (Launch is a success).

**Comment by skjelten** [comment]
Since we have moved to a GUI based emulator where the config file is no longer manually edited, I'll just close this issue.

@trevor0402 : Regarding your offer to help, there is a ton of stuff to work on! :slightly_smiling_face:  It is on my TODO list to write a status page where it is easier to see current status vs the real hardware, but feel free to explore the code base and suggest improvements in separate issues. All help is greatly appreciated!
