### ISSUE TITLE
Roland SCC-1 support

### ISSUE THREAD

**Issue by DMJC** [skjelten/emusc#9]
SCC-1 is an SC-55 as a PC add-in card. Would be worth adding support for it. SCC-1A is the SC-55 MK2 equivalent card. I've started to add support for this, It looks like it mostly works. I would like some assistance with it.
This is the output I get, All I did was add two new entries in the enums for control roms and  updated the control rom scan for SCC1... I'm playing Wing Commander 3 DOS Midis (made for Sound Canvas/work in EMUSC) and they do playback with the SCC-1 Roms! Just getting this illegal drum set message.

EmuSC: SCC-1 control ROM found [version==1.3 date=]
EmuSC: PCM ROM(s) found and decrypted [version=1.20 date=1991-01-11]
EmuSC: GS mode initialized
EmuSC: MIDI sequencer [ALSA] client started at address 128
EmuSC: Audio output [PulseAudio] successfully initialized
 -> s16le 2ch 44100Hz
EmuSC: MIDI input event [Port subscribed]
EmuSC: Illegal program for drum set (48)
EmuSC: Illegal program for drum set (48)

**Comment by skjelten** [comment]
Fixed as of your own PR #10 (thanks!). Closing.
